[package]
name = "effektio"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cbindgen = "0.14.3"
dart-bindgen = "0.1.7"

[dependencies]
anyhow = "1.0.51"
tokio = { version = "1", features = ["rt-multi-thread"] }
ffi-gen-macro = { version = "0.1.2" }
futures = "0.3.17"
ffi_helpers = "0.2"
allo-isolate = "0.1.6"
lazy_static = "1.4"
async-std = "1"

[lib]
name = "effektio"
crate-type = ["staticlib"]
