on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: App

env:
  RELEASE: true

jobs:

  build-android:
    runs-on: ubuntu-latest
    name: Build Android
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - uses: nttld/setup-ndk@v1
        with:
          # FIXME: cargo-ndk doesn't work with latest
          ndk-version: r22
      - run: |
          cargo install cargo-make
          cargo make setup-android
      - uses: subosito/flutter-action@v2
        name: "Set up flutter"
        with:
          channel: 'stable'
      - name: Build Android FFI
        run: cargo make --profile release android-arm
      - name: Ensure ffi-interface is up to date
        run: git diff --exit-code  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
      - run: flutter build apk --target-platform android-arm64 --release
        working-directory: ./app

  build-ios:
    runs-on: macos-latest
    name: Build iOS
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo install cargo-make
          cargo make setup-ios
      - uses: subosito/flutter-action@v2
        name: "Set up flutter"
        with:
          channel: 'stable'
      - name: Build iOS FFI
        run: cargo make --profile release  ios
      - name: Ensure ffi-interface is up to date
        run: git diff --exit-code  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
      - run: flutter build ios --release --no-codesign
        working-directory: ./app

  integration-test:
    runs-on: ubuntu-latest
    name: Integration Tests
    continue-on-error: true
    services:
      synapse:
        image: "lightyear/effekio-synapse-ci:latest"
        volumes:
          - synapse-data:/data
        env:
          SYNAPSE_SERVER_NAME: ds9.effektio.org
          SYNAPSE_REPORT_STATS: no
        ports: 
          - 8008:8008
          - 8009:8009
          - 8448:8448
    steps:
      - uses: actions/checkout@v2
      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - run: |
          cargo install cargo-make
      - uses: subosito/flutter-action@v2
        name: "Set up flutter"
        with:
          channel: 'stable'
      - name: Build Native
        run: cargo make --profile release desktop
      - name: Ensure ffi-interface is up to date
        run: git diff --exit-code  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
      - run: flutter test -d linux integration_test/*  --dart-define DEFAULT_EFFEKTIO_SERVER=http://localhost:${{ job.services.synapze.ports['8008'] }}
        name: "running tests"
        working-directory: ./app